### PR TITLE
Setting 5sec delay on delete/update comment

### PR DESCRIPTION
**Pull request by james2432**
Fixes https://github.com/j0be/PowerDeleteSuite/issues/36

Adds deletion and comment editing delay, due to rate limiting set by reddit api

### CODE REVIEW

**Comment by nhooyr** [comment]
Looks reasonable to me.

**Comment by blhoward2** [comment]
I understand this is Reddit's doing, but this makes nuking a large number of comments super slow. Are you sure that a 5 second delay is shortest would work? Given how I understand this script works (which is cursory), is this even affected by Reddit's recent rate limiting?

**Comment by james2432** [comment]
5 is the shortest. You can even see this on the interface when you delete a bunch of stuff manually very quickly it will say something to the effect of try again in 4 seconds, I tried 4 I would get missed comments even at 4.5.

**Comment by blhoward2** [comment]
Weird. I just forked this, removed it, and deleted 3,000 comments without the delay without a single error or issue.

**Comment by blhoward2** [comment]
Not sure why the thumbs down. Have you re-tested it again without? Maybe you were personally rate limited at the time? I have now used it on three accounts without the delay, without issue.

**Comment by suodrazah** [comment]
I have also successfully deleted 1000s of objects with no errors or rate limiting.

**Comment by Obelisx** [comment]
> Not sure why the thumbs down. Have you re-tested it again without? Maybe you were personally rate limited at the time? Maybe Reddit removed whatever limit was being hit? I have now used it on three accounts without the delay, without issue.
> 
> You can use my fork if you want to test it. I copied over the code pen and such so it installs the same way.



> I have also successfully deleted 1000s of objects with no errors or rate limiting.

Does it succesfully edit the comments before removal without the 5 sec delay?

**Comment by David-Bumpus** [comment]
> Weird. I just forked this, removed it, and deleted 3,000 comments without the delay without a single error or issue. Given how to the backend this appears to be the user in the UI, I'm not sure how they could ever force a 5 second delay between calls.

The delete works without the delay, but you can't edit & delete without the delay, the edit won't stick.
Also you can't mass-edit without the delay for a similar reason. Thanks reddit...

**Comment by blhoward2** [comment]
The edits stuck on mine.

**Pull request merged**
