### PR TITLE
fixed css stylesheet 403 error

### PR DESCRIPTION
**Pull request by mykola2312**
So my account was banned and PowerDeleteSuite keep saying [this error](https://github.com/j0be/PowerDeleteSuite/issues/30)

It was a surprise for me that for script working you need load css from reddit page, which I couldn't being banned from reddit. The fix was replacing reddit url to github one

I urge you to merge this PR or patch it so it doesnt loads anything from reddit and therefore allows banned users to delete their posts and comments.
I tested it and it in fact deleted everything.

### CODE REVIEW

**Comment by j0be** [comment]
oh, that's a fun little wrinkle. I'll review this in a bit

**Comment by mykola2312** [comment]
Hello. How is it going?

**Comment by mykola2312** [comment]
Hello @j0be 

I again urge You to merge this PR or apply other sufficient measures in other resolve css stylesheet loading. You must understand that You are providing most important security and privacy tools to mass-delete data from reddit to prevent stalking. If You dont want to rely on my raw github link - You easily could replace with Your one. Remember that You should not load any files from any subreddit, since user could be banned on reddit. People depend on You. Good luck.

**Comment by TheMrRandomDude** [comment]
@mykola2312 Hi, just for clarification, you said:

>which I couldn't being <ins>**banned**</ins> from reddit. The fix was replacing reddit url to github one
> 
> I urge you to merge this PR or patch it so it doesn't load anything from reddit and therefore allows <ins>**banned users**</ins> to delete their posts and comments. I tested it and it in fact deleted everything.

You mean suspended, right? As far as I know, banned users can't even log in since they're - banned.

**Comment by mykola2312** [comment]
> @mykola2312 Hi, just for clarification, you said:
> 
> >which I couldn't being <ins>**banned**</ins> from reddit. The fix was replacing reddit url to github one
> > 
> > I urge you to merge this PR or patch it so it doesn't load anything from reddit and therefore allows <ins>**banned users**</ins> to delete their posts and comments. I tested it and it in fact deleted everything.
> 
> You mean suspended, right? As far as I know, banned users can't even log in since they're - banned.

Greetings @j0be 

I have this message when log in to reddit:
"This account has been permanently banned. Check your inbox for a message with more information."

So, I can login into my reddit account and subreddits. In fact, I can even subscribe to new subreddits. But I cant make posts, comments and upvotes.

So my reddit account is quite functional yet

**Comment by TheMrRandomDude** [comment]
@mykola2312 Ah, interesting. So you were banned before using PowerDeleteSuite, now beacuse of using PowerDeleteSuite. That's what I was curious about. Thank you.

**Comment by mykola2312** [comment]
> @mykola2312 Ah, interesting. So you were banned before using PowerDeleteSuite, now beacuse of using PowerDeleteSuite. That's what I was curious about. Thank you.

@TheMrRandomDude I was not banned for using PowerDeleteSuite, it was for making "fake accounts". PowerDeleteSuite still could be used to delete all posts, since I can do this manually. This PR is about fixing bug that prevented me using PowerDeleteSuite

**Comment by SuperTurn** [comment]
So this is still an issue for suspended/banned accounts? Anyone else have another tool they recommend since this hasn't been addressed since being opened in December 2022? 

https://github.com/j0be/PowerDeleteSuite/issues/30

**Comment by mykola2312** [comment]
> So this is still an issue for suspended/banned accounts? Anyone else have another tool they recommend since this hasn't been addressed since being opened in December 2022?
> 
> #30

@SuperTurn Yes. But you don't need other tools, my fork works flawlessly. [https://github.com/mykola2312/PowerDeleteSuite](https://github.com/mykola2312/PowerDeleteSuite)

What You could do, is urge @j0be to consider merging and fixing this issue, before that - use my fork.

**Comment by mykola2312** [comment]
Thanks to everyone who assisted in bringing this fix into mainstream repo. You made this world a bit better in terms of privacy

**Comment by XOIIO** [comment]
@mykola2312 Hey there, I ran into this exact same problem, and your workaround works mostly, however when editing comments it seems flakey and won't actually use custom text, just the generic preset ones. 

I swapped the github URL to a local js file to fix this with my own set text entries, but it still errors out calling a github check. Not much of a javascript guy, but what would the needed tweaks to the bookmark need to be to just use a local file?

**Comment by mykola2312** [comment]
> github URL to a local js file

You can't do that as far as I know. Fork repo and replace github url with url, pointing to your github repo. Do the adjustments. Remember that browser can't just read local files.

**Comment by JunctionRunner** [comment]
Guess I'll have to give that a shot, the script does successfully load in part from a local copy, seems like it would be the same as working with a local webpage you're building. 

Not sure why it's not editing comments with what I enter, unless there's a character limit in the script.

**Pull request merged**
