### PR TITLE
Fix comment hashtag issue

### LINKED ISSUE #34: Export stops after hashtag
I've "prepared for export" my whole reddit account and the results page says something about 2901 exported entries.

Yet when downloading the items, I get only 23 items with the last one being [this one](https://www.reddit.com/r/RedditAlternatives/comments/13r2rv1/how_do_you_feel_about_using_the_fediverse_as_a/jlkh87v/) and truncated at the `#`. The whole line in the CSV looks like this:

    "","You can also follow hashtags, e.g.

And that's the end of the downloaded file.

This is with Firefox 114.0 on macOS.

### PR DESCRIPTION
**Pull request by biran4454**
Fix hashtags from ending the file too early.
Closes #34 and possibly #20.

### CODE REVIEW

**Comment by biran4454** [comment]
I considered replacing # with a hyphen or other symbol, however I opted for removing the hashtag entirely since I felt it was unlikely to cause too much of an issue.  
In retrospect however it may interfere with the MD syntax for headings, let me know what you think.

**Comment by j0be** [comment]
Replace it with "%23" and I'll get that merged

**Comment by j0be** [comment]
That bug is actually caused because it's a part of an href, which makes it parsed as a URL. Technically, PDS should really run `encodeURIComponent()` on every comment value, but this at least fixes hashes

**Comment by biran4454** [comment]
> Replace it with "%23" and I'll get that merged

Done! Not sure why I didn't do this in the first place haha.

**Pull request merged**
